name: Build Opus

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code with full history
      uses: actions/checkout@v3
      with:
        fetch-depth: 0  # Ensures all branches and history are available

    - name: Install build dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y autoconf automake libtool pkg-config make gcc

    - name: Prepare build system
      run: |
        ./autogen.sh || true  # in case it's already bootstrapped

    - name: Configure with custom modes
      run: ./configure --enable-custom-modes --with-pic

    - name: Build
      run: make -j$(nproc)

    - name: Archive build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: opus-build
        path: .libs/  # or wherever the compiled .so/.a files go
