name: Build Opus

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y autoconf automake libtool pkg-config make gcc

    - name: Configure and build
      run: |
        ./autogen.sh || true
        ./configure --enable-custom-modes --with-pic
        make -j$(nproc)

    - name: Archive build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: opus-build
        path: .libs/  # یا مسیر دلخواه دیگر به خروجی libopus
